[package]
name = "gtk-space-invaders"
version = "0.1.0"
authors = ["Aurélien Richez <aurelien.richez@gmail.com>"]

[dependencies]
space-invaders-core = { path = "../space-invaders-core"}
intel-8080-emu = "0.1"
gtk = "0.5.0"
cairo-rs = "*"
gdk = "0.9.0"