[package]
name = "gtk-space-invaders"
version = "0.1.0"
authors = ["Aurélien Richez <aurelien.richez@gmail.com>"]

[dependencies]
intel-8080-emu = { path = "../intel-8080-emu"}
space-invaders-core = { path = "../space-invaders-core"}
gtk = "0.4.1"
cairo-rs = "^0"
gdk = "^0"